# Generated by Django 3.2.12 on 2022-03-02 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_f_name', models.CharField(max_length=20)),
                ('u_m_name', models.CharField(max_length=20)),
                ('u_l_name', models.CharField(max_length=20)),
                ('u_email', models.CharField(max_length=30)),
                ('u_phone', models.CharField(max_length=10)),
                ('u_username', models.CharField(max_length=20)),
                ('u_pass', models.CharField(max_length=32)),
                ('is_img_registered', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
