# Generated by Django 3.2.12 on 2025-03-23 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_details',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_details', models.TextField()),
                ('e_code', models.CharField(max_length=32)),
                ('e_staus', models.SmallIntegerField(default=0)),
                ('e_faculty', models.CharField(max_length=32)),
                ('e_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='examinee_details',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex_username', models.CharField(max_length=20)),
                ('ex_code', models.CharField(max_length=32)),
                ('ex_staus', models.SmallIntegerField(default=0)),
                ('ex_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_f_name', models.CharField(max_length=20)),
                ('u_m_name', models.CharField(max_length=20)),
                ('u_l_name', models.CharField(max_length=20)),
                ('u_email', models.CharField(max_length=30)),
                ('u_phone', models.CharField(max_length=10)),
                ('u_username', models.CharField(max_length=20)),
                ('u_pass', models.CharField(max_length=32)),
                ('is_img_registered', models.IntegerField(default=0)),
                ('u_role', models.IntegerField(default=1, editable=False)),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('u_facl', models.CharField(max_length=30)),
            ],
        ),
    ]
